#!/usr/bin/env bash

# Usage: run_all_tests [-v]
# Runs all .li tests under test/, using run_test, and reports pass/fail summary.

red='\033[31m'
bold_red='\033[1;31m'
green='\033[32m'
bold_green='\033[1;32m'
blue='\033[34m'
bold_blue='\033[1;34m'
nc='\033[0m'

if [[ ! -d "test" ]]; then
  echo "Tests directory does not exist."
  exit 1
fi

run_test="$(dirname "$0")/run_test"
cd "$(dirname "$run_test")" || exit 1

cd test || exit 1
mapfile -t test_files < <(find . -type f -name '*.li' | sed 's|^./||' | sort)
cd ..

if [[ ${#test_files[@]} -eq 0 ]]; then
  echo -e "${red}error${nc}: no test files found."
  exit 1
fi

echo -e "${blue}╭────────────────────────────────────────────╮${nc}"
echo -e "${blue}│               ${bold_blue}Running Tests                │${nc}"
echo -e "${blue}╰────────────────────────────────────────────╯${nc}"

did_fail=0
for test_file in "${test_files[@]}"; do
  test_name="${test_file%.li}"
  "$run_test" "$test_name"
  if [[ $? -ne 0 ]]; then
    did_fail=1
  fi
done

if [[ $did_fail -eq 1 ]]; then
    echo -e "${red}╭────────────────────────────────────────────╮${nc}"
    echo -e "${red}│             ${bold_red}Some tests failed              │${nc}"
    echo -e "${red}╰────────────────────────────────────────────╯${nc}"
    exit 1
else
    echo -e "${green}╭────────────────────────────────────────────╮${nc}"
    echo -e "${green}│             ${bold_greeen}All tests passed!              │${nc}"
    echo -e "${green}╰────────────────────────────────────────────╯${nc}"
    exit 0
fi