#!/usr/bin/env bash

# strip out the current directory from PATH
if [[ -z "$PATH" ]]; then
  echo "PATH is not set. Exiting."
  exit 1
fi
PATH=$(echo "$PATH" | tr ':' '\n' | grep -v -x '\.' | paste -sd:)

# basic make wrapper to use all cores, just use like make.
make -j$(nproc) $@ || exit 1